steps:
  - plugins:
      - golang-cross-compile#v1.3.0:
          build: main.go
          import: github.com/terraform-providers/terraform-provider-dme
          targets:
            - version: "1.11"
              goos: linux
              goarch: amd64
            - version: "1.11"
              goos: darwin
              goarch: amd64
              gomodule: "on"
